### ISSUE TITLE
Plans to move from airlift embedded database

### ISSUE THREAD

**Issue by xsalefter** [killbill/killbill-oss-parent#552]
Currently, we're using embedded database server for [MySQL](https://github.com/airlift/testing-mysql-server) and [postgreSQL](https://github.com/airlift/testing-postgresql-server). Unfortunately, those library in "public archive" state, so it is unlikely that we can even send a PR: There's case that we need to update postgreSQL version to test make sure we able to upgrade JOOQ library. Current [testing-postgresql-server](https://github.com/airlift/testing-postgresql-server/blob/master/repack-postgres.sh#L9) version doesn't support `fetch ... row only` statement, where `JOOQ  3.15.x` will use that statement.

So this leave us with:

1. ~Use `testcontainer`. Problem is experience tell me that this is slow compared to use local/installed/embedded.~
2. Fork those embedded server library to `killbill-commons`.

~Current plan: Lets use `testcontainer` in smaller project like stripe/braintree plugins. If it’s too slow/painful, maybe we just fork them.~

We had this [updated plan](https://github.com/killbill/killbill-oss-parent/issues/552#issuecomment-1276752397), but a comment section is not a quite right place to put a (bigger) plan, so I decided with 2 sub-tasks:

- #619
- #620

**Comment by xsalefter** [comment]
Update in Fork vs `testcontainers`:

### Fork

At least for postgresql, we [need to download](https://github.com/airlift/testing-postgresql-server/blob/master/repack-postgres.sh) binary from enterprisedb. Page in [enterprisedb](https://www.enterprisedb.com/products-services-training/pgbindownload) show that we have limited postgreSQL binary. At the time of writing, only postgresql v.10.22 that is available for linux. `fetch ... row only` [supported by postgresql 10](https://www.postgresql.org/docs/10/sql-fetch.html), but if we want to go with postgresql > v.10.22, we may need to build it from source.

### Testcontainers

TD;LR: Testcontainers need `docker-machine`, but officially, [docker-machine deprecated](https://github.com/docker/roadmap/issues/245) a year ago. There are fork by [rancher](https://github.com/rancher/machine) and [gitlab](https://gitlab.com/gitlab-org/ci-cd/docker-machine). There's also [request to remove docker in testcontainers](https://github.com/testcontainers/testcontainers-java/issues/4664).

**Comment by xsalefter** [comment]
We going to 2 different paths:
- for postgres, we use zonkyio's [emdedded postgre](https://github.com/zonkyio/embedded-postgres).
- we will fork Airlift's `testing-mysql-server`. 

### Update plan:

1. Update oss-parent to have `embedded-postgres` and add <jooq.version />, sent PR
2. While waiting PR in [1], test `embedded-postgres` against killbill locally with modified `killbill-commons` using server from embedded-postgres instead of airlift.
3. While testing in [2], work on fork of `mysql-testing-server`, and test against `killbill-stripe-plugin`
4. Test work on [3] against `killbill` with modified `killbill-commons` using server from our `mysql-testing-server` instead of airlift.

When everything passed:

1. Make sure that our `mysql-testing-server` is available at least in sonatype.
2. Update `oss-parent`:
   - Remove all airlift dependencies
   - add our `mysql-testing-server`
   and wait until available in sonatype.
3. Update `killbill-commons`, `killbill-platform` to use latest `oss-parent`, test them (Do not send PR yet)
4. Test `killbill`
5. Test our stripe and braintree plugins

When everything passed

1. Send PR for `killbill-commons` and `killbill-platform` with latest `oss-parent`.
2. Update `killbill`, stripe, and braintree with latest `oss-parent`, and send PR

**Comment by xsalefter** [comment]
### Known Embedded Postgres issue (When integrating with Killbill)

#### A lot of stacktrace after unexpected exception

When running `slow` test in `killbill` (with using `embedded-postgres` in `killbill-commons`), I encounter this exception:

```java
.... 
[ERROR] Tests run: 755, Failures: 1, Errors: 0, Skipped: 754, Time elapsed: 5.081 s <<< FAILURE! - in TestSuite
[ERROR] org.killbill.billing.jaxrs.TestPerTenantConfig.beforeSuite  Time elapsed: 4.512 s  <<< FAILURE!
java.lang.NoClassDefFoundError: javax/annotation/Priority
	at org.glassfish.jersey.model.internal.RankedProvider.computeRank(RankedProvider.java:87)
	at org.glassfish.jersey.model.internal.RankedProvider.<init>(RankedProvider.java:48)
	at org.glassfish.jersey.internal.inject.Injections.lookupService(Injections.java:89)

....
```
That's the real problem that need to tackle, but after that, there's a lot of stacktrace that coming up after. That stacktrace showing up more than 800 times that it is cluttered and make it hard to find what is the real problem. 

Seems like It is works as intended (shutdown database and fail-fast), but ~800 attempt to get connection may indicating that fail-fast not archived properly.

Below is one of them:

```java
....

2022-10-14T21:04:35,712+0000 lvl='WARN', log='DefaultQueueLifecycle', th='notifications-lifecycle-dispatcher-th-1', xff='', rId='', tok='', aRId='', tRId='', notifications: 
  Thread notifications-lifecycle-dispatcher-th-1 got DBIException exception: 
  org.skife.jdbi.v2.exceptions.UnableToObtainConnectionException: org.postgresql.util.PSQLException: Connection to localhost:37747 refused. 
  Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.skife.jdbi.v2.DBI.open(DBI.java:251)
	at org.skife.jdbi.v2.DBI.open(DBI.java:219)
	at org.skife.jdbi.v2.DBI.withHandle(DBI.java:300)
	at org.skife.jdbi.v2.DBI.inTransaction(DBI.java:328)
	at org.killbill.queue.DBBackedQueue.executeTransaction(DBBackedQueue.java:343)
	at org.killbill.queue.DBBackedQueueWithPolling.getReadyEntries(DBBackedQueueWithPolling.java:71)
	at org.killbill.notificationq.NotificationQueueDispatcher.getReadyNotifications(NotificationQueueDispatcher.java:287)
	at org.killbill.notificationq.NotificationQueueDispatcher.doDispatchEvents(NotificationQueueDispatcher.java:217)
	at org.killbill.queue.DefaultQueueLifecycle.withHandlingRuntimeException(DefaultQueueLifecycle.java:367)
	at org.killbill.queue.DefaultQueueLifecycle$DispatcherRunnable.run(DefaultQueueLifecycle.java:301)
	at org.killbill.commons.concurrent.WrappedRunnable.run(WrappedRunnable.java:49)
	....
	at java.base/java.lang.Thread.run(Thread.java:834)

Caused by: org.postgresql.util.PSQLException: Connection to localhost:37747 refused. 
  Check that the hostname and port are correct and that the postmaster is accepting TCP/IP connections.
	at org.postgresql.core.v3.ConnectionFactoryImpl.openConnectionImpl(ConnectionFactoryImpl.java:319)
	at org.postgresql.core.ConnectionFactory.openConnection(ConnectionFactory.java:49)
	at org.postgresql.jdbc.PgConnection.<init>(PgConnection.java:247)
	at org.postgresql.Driver.makeConnection(Driver.java:434)
	at java.sql/java.sql.DriverManager.getConnection(DriverManager.java:228)
	at org.postgresql.ds.common.BaseDataSource.getConnection(BaseDataSource.java:103)
	at org.killbill.billing.DBTestingHelper$RetryableDataSource.getConnection(DBTestingHelper.java:130)
	at org.skife.jdbi.v2.DataSourceConnectionFactory.openConnection(DataSourceConnectionFactory.java:40)
	at org.skife.jdbi.v2.DBI$4.execute(DBI.java:230)
	at org.skife.jdbi.v2.DBI$4.execute(DBI.java:227)
	at org.killbill.commons.profiling.Profiling.executeWithProfiling(Profiling.java:35)
	at org.skife.jdbi.v2.DBI.open(DBI.java:227)
	... 15 common frames omitted
Caused by: java.net.ConnectException: Connection refused (Connection refused)
	at java.base/java.net.PlainSocketImpl.socketConnect(Native Method)
	at java.base/java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:399)
	at java.base/java.net.SocksSocketImpl.connect(SocksSocketImpl.java:403)
	at java.base/java.net.Socket.connect(Socket.java:591)
	at org.postgresql.core.PGStream.createSocket(PGStream.java:241)
	at org.postgresql.core.PGStream.<init>(PGStream.java:98)
	... 30 common frames omitted
```

**Comment by xsalefter** [comment]
Done.
